[package]
name = "auto-jumpking"
version = "0.1.0"
authors = ["Jil Sahm"]
edition = "2018"
build = "build.rs"

[dependencies]
env_logger = "0.5.3"
lazy_static = "1.4.0"
log = "0.4.1"
regex = "1.3.1"
winapi = { version = "0.3.8", features = ["windef", "winuser"] }